from detectron2.data.datasets import register_coco_instances
import datetime
from config import  TRAFFIC_SIGN_ANNOT_TRAIN_JSON,  PATH_TRAIN_IMG, NAME_TRAIN, \
TRAFFIC_SIGN_ANNOT_VALID_JSON, PATH_VALID_IMG, NAME_VALID, \
TRAFFIC_SIGN_ANNOT_TEST_JSON, PATH_TEST_IMG, NAME_TEST

register_coco_instances(NAME_TRAIN, {}, TRAFFIC_SIGN_ANNOT_TRAIN_JSON, PATH_TRAIN_IMG)
register_coco_instances(NAME_VALID, {}, TRAFFIC_SIGN_ANNOT_VALID_JSON, PATH_VALID_IMG)
register_coco_instances(NAME_TEST, {}, TRAFFIC_SIGN_ANNOT_TEST_JSON, PATH_TEST_IMG)
